[package]
name = "respi"
version = "0.1.0"
authors = ["Heinrich Lunemann <hw.lunemann@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.0"
csv = "1.1.6"
err-derive = "0.3.0"
